server:
  port: 10002

spring:
  datasource:
    url: jdbc:mysql://192.168.56.109:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456
  redis:
    database: 0
    host: 192.168.56.109
    port: 6379
  rabbitmq:
    host: 192.168.56.109
    port: 5672
    username: guest
    password: guest
