server:
  port: 10005

spring:
  application:
    name: foodie-auth-service
  redis:
    database: 0
    host: localhost
    port: 6379
  zipkin:
    # 启用服务发现
    discovery-client-enabled: true
    base-url: http://ZIPKIN-SERVER/
    # 启用通过服务发现定位主机名
    locator:
      discovery:
        enabled: true
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    # 服务注册中心地址
    service-url:
      defaultZone: http://localhost:20000/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
